# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Info Mundo
email: favs1969@gmail.com
description: Sobre mim e sobre o mundo.
baseurl: "/infomundo"
url: "" # the base hostname & protocol for your site
twitter_username: franzisk
github_username:  franzisk

# Build settings
markdown: kramdown
permalink: /:title
